version: '3'
services:
  # Backend service
  backend:
    build:
      context: ../src/backend
      dockerfile: ../../deployment/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    volumes:
      - ../src/backend:/app
    restart: unless-stopped
    networks:
      - incalmo-network

  # Frontend service
  frontend:
    build:
      context: ../frontend
      dockerfile: ../deployment/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=${API_BASE_URL:-http://localhost:8000}
      - REACT_APP_WS_BASE_URL=${WS_BASE_URL:-ws://localhost:8000}
    restart: unless-stopped
    networks:
      - incalmo-network

networks:
  incalmo-network:
    driver: bridge
